export function DataForm(formData) {

 let clientData = {
    // name: formData.name,
    email: formData.email,
    phone: formData.phone,
    address: formData.address,
    city: formData.city,
    postal: formData.postal,
    province: formData.province,
    dl: formData.dl,
    userId: formData.userId,
    financeId: formData.financeId,
    dashboardId: formData.dashboardId,
  };
  /*financeData = {
     ...formData,
   }
   */
 let financeData = {
    //	clientfileId
    date: formData.date,
    name: formData.name,
    firstName: formData.firstName,
    lastName: formData.lastName,
    email: formData.email,
    phone: formData.phone,
    address: formData.address,
    city: formData.city,
    timeOfDay: formData.timeOfDay,
    timeToContact: formData.timeToContact,
    typeOfContact: formData.typeOfContact,
    clientfileId: formData.clientfileId,

    financeId: formData.financeId,
    iRate: formData.iRate,
    months: formData.months,
    discount: formData.discount,
    total: formData.total,
    onTax: formData.onTax,
    on60: formData.on60,
    biweekly: formData.biweekly,
    weekly: formData.weekly,
    weeklyOth: formData.weeklyOth,
    biweekOth: formData.biweekOth,
    oth60: formData.oth60,
    weeklyqc: formData.weeklyqc,
    biweeklyqc: formData.biweeklyqc,
    qc60: formData.qc60,
    deposit: formData.deposit,
    biweeklNatWOptions: formData.biweeklNatWOptions,
    weeklylNatWOptions: formData.weeklylNatWOptions,
    nat60WOptions: formData.nat60WOptions,
    weeklyOthWOptions: formData.weeklyOthWOptions,
    biweekOthWOptions: formData.biweekOthWOptions,
    oth60WOptions: formData.oth60WOptions,
    biweeklNat: formData.biweeklNat,
    weeklylNat: formData.weeklylNat,
    nat60: formData.nat60,
    qcTax: formData.qcTax,
    otherTax: formData.otherTax,
    totalWithOptions: formData.totalWithOptions,
    otherTaxWithOptions: formData.otherTaxWithOptions,
    desiredPayments: formData.desiredPayments,
    freight: formData.freight,
    admin: formData.admin,
    commodity: formData.commodity,
    pdi: formData.pdi,
    discountPer: formData.discountPer,
    userLoanProt: formData.userLoanProt,
    userTireandRim: formData.userTireandRim,
    userGap: formData.userGap,
    userExtWarr: formData.userExtWarr,
    userServicespkg: formData.userServicespkg,
    deliveryCharge: formData.deliveryCharge,
    vinE: formData.vinE,
    lifeDisability: formData.lifeDisability,
    rustProofing: formData.rustProofing,
    userOther: formData.userOther,
    paintPrem: formData.paintPrem,
    licensing: formData.licensing,
    stockNum: formData.stockNum,
    options: formData.options,
    accessories: formData.accessories,
    labour: formData.labour,
    year: formData.year,
    brand: formData.brand,
    model: formData.model,
    model1: formData.model1,
    color: formData.color,
    modelCode: formData.modelCode,
    msrp: formData.msrp,
    userEmail: formData.userEmail,
    tradeValue: formData.tradeValue,
    tradeDesc: formData.tradeDesc,
    tradeColor: formData.tradeColor,
    tradeYear: formData.tradeYear,
    tradeMake: formData.tradeMake,
    tradeVin: formData.tradeVin,
    tradeTrim: formData.tradeTrim,
    tradeMileage: formData.tradeMileage,
    trim: formData.trim,
    vin: formData.vin,
  };

 let dashData = {
    //	financeId
    userEmail: formData.userEmail,
    referral: formData.referral,
    visited: formData.visited,
    clientfileId: formData.clientfileId,
    financeId: formData.financeId,
    bookedApt: formData.bookedApt,
    aptShowed: formData.aptShowed,
    aptNoShowed: formData.aptNoShowed,
    testDrive: formData.testDrive,
    metService: formData.metService,
    metManager: formData.metManager,
    metParts: formData.metParts,
    sold: formData.sold,
    depositMade: formData.depositMade,
    refund: formData.refund,
    turnOver: formData.turnOver,
    financeApp: formData.financeApp,
    approved: formData.approved,
    signed: formData.signed,
    pickUpSet: formData.pickUpSet,
    demoed: formData.demoed,
    delivered: formData.delivered,
    lastContact: formData.lastContact,
    status: formData.status,
    customerState: formData.customerState,
    result: formData.result,
    timesContacted: formData.timesContacted,
    nextAppointment: formData.nextAppointment,
    completeCall: formData.completeCall,
    followUpDay: formData.followUpDay,
    state: formData.state,
    deliveredDate: formData.deliveredDate,
    notes: formData.notes,
    visits: formData.visits,
    progress: formData.progress,
    metSalesperson: formData.metSalesperson,
    metFinance: formData.metFinance,
    financeApplication: formData.financeApplication,
    pickUpDate: formData.pickUpDate,
    pickUpTime: formData.pickUpTime,
    depositTakenDate: formData.depositTakenDate,
    docsSigned: formData.docsSigned,
    tradeRepairs: formData.tradeRepairs,
    seenTrade: formData.seenTrade,
    lastNote: formData.lastNote,
    dLCopy: formData.dLCopy,
    insCopy: formData.insCopy,
    testDrForm: formData.testDrForm,
    voidChq: formData.voidChq,
    loanOther: formData.loanOther,
    signBill: formData.signBill,
    ucda: formData.ucda,
    tradeInsp: formData.tradeInsp,
    customerWS: formData.customerWS,
    otherDocs: formData.otherDocs,
    urgentFinanceNote: formData.urgentFinanceNote,
    funded: formData.funded,
    countsInPerson: formData.countsInPerson,
    countsPhone: formData.countsPhone,
    countsSMS: formData.countsSMS,
    countsOther: formData.countsOther,
    countsEmail: formData.countsEmail,
  };
 let financeId = formData.id
  return { financeId, clientData, dashData, financeData };
  //import { clientData, dashData, financeData, financeId: finance.id } from "~components/dashboard/calls/actions/dbData.tsx";

}
