import { json, type ActionFunction, type LoaderFunction } from '@remix-run/node';
import { getSession, commitSession } from '~/sessions/auth-session.server';
import { GetUser } from '~/utils/loader.server';
import financeFormSchema from '~/overviewUtils/financeFormSchema';
import { prisma } from '~/libs';

export async function loader({ request, params }: LoaderFunction) {
  const users = await prisma.clientfile.findMany({
    select: {
      id: true,
      createdAt: true,
      updatedAt: true,
      financeId: true,
      userId: true,
      firstName: true,
      lastName: true,
      name: true,
      email: true,
      phone: true,
      address: true,
      city: true,
      postal: true,
      province: true,
      dl: true,
      typeOfContact: true,
      timeToContact: true,
      conversationId: true,
      billingAddress: true,

      AccOrder: {
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          userEmail: true,
          userName: true,
          dept: true,
          sellingDept: true,
          total: true,
          discount: true,
          discPer: true,
          paid: true,
          paidDate: true,
          status: true,
          workOrderId: true,
          note: true,
          financeId: true,
          clientfileId: true,

          AccHandoff: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              sendTo: true,
              handOffTime: true,
              status: true,
              sendToCompleted: true,
              completedTime: true,
              notes: true,
              handOffDept: true,
              AccOrderId: true,
            }
          },

          AccessoriesOnOrders: {
            select: {
              id: true,
              quantity: true,
              accOrderId: true,
              status: true,
              orderNumber: true,
              OrderInvId: true,
              accessoryId: true,
              service: true,
              hour: true,

              accessory: {
                select: {
                  id: true,
                  createdAt: true,
                  updatedAt: true,
                  partNumber: true,
                  brand: true,
                  name: true,
                  price: true,
                  cost: true,
                  quantity: true,
                  minQuantity: true,
                  description: true,
                  category: true,
                  subCategory: true,
                  onOrder: true,
                  distributer: true,
                  location: true,
                  note: true,
                  workOrderSuggestion: true,
                }
              }
            }
          },

          Payments: {
            select: {
              id: true,
              createdAt: true,
              paymentType: true,
              cardType: true,
              amountPaid: true,
              cardNum: true,
              receiptId: true,
              financeId: true,
              userEmail: true,
              accOrderId: true,
              workOrderId: true,
            }
          },
        },
      },

      WorkOrder: {
        select: {
          workOrderId: true,
          unit: true,
          mileage: true,
          vin: true,
          tag: true,
          motor: true,
          color: true,
          budget: true,
          waiter: true,
          totalLabour: true,
          totalParts: true,
          subTotal: true,
          total: true,
          writer: true,
          userEmail: true,
          tech: true,
          techEmail: true,
          notes: true,
          customerSig: true,
          status: true,
          location: true,
          quoted: true,
          paid: true,
          remaining: true,
          FinanceUnitId: true,
          ServiceUnitId: true,
          financeId: true,
          clientfileId: true,
          note: true,
          closedAt: true,
          createdAt: true,
          updatedAt: true,

          FinanceUnit: {
            select: {
              paintPrem: true,
              licensing: true,
              stockNum: true,
              options: true,
              accessories: true,
              freight: true,
              labour: true,
              year: true,
              brand: true,
              mileage: true,
              model: true,
              model1: true,
              color: true,
              modelCode: true,
              msrp: true,
              trim: true,
              vin: true,
              bikeStatus: true,
              invId: true,
              location: true,
              id: true,
              createdAt: true,
              updatedAt: true,
              financeId: true,
            }
          },

          ServiceUnit: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              price: true,
              brand: true,
              model: true,
              color: true,
              accessories: true,
              options: true,
              year: true,
              vin: true,
              trim: true,
              mileage: true,
              location: true,
              condition: true,
              repairs: true,
              stockNum: true,
              motor: true,
              tag: true,
              licensing: true,
              tradeEval: true,
              clientfileId: true,
            }
          },

          AccOrders: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              userEmail: true,
              userName: true,
              dept: true,
              sellingDept: true,
              total: true,
              discount: true,
              discPer: true,
              paid: true,
              paidDate: true,
              status: true,
              workOrderId: true,
              note: true,
              financeId: true,
              clientfileId: true,
              AccessoriesOnOrders: {
                select: {
                  id: true,
                  quantity: true,
                  accOrderId: true,
                  status: true,
                  orderNumber: true,
                  OrderInvId: true,
                  accessoryId: true,
                  service: true,
                  hour: true,
                }
              },
              Payments: {
                select: {
                  id: true,
                  createdAt: true,
                  paymentType: true,
                  cardType: true,
                  amountPaid: true,
                  cardNum: true,
                  receiptId: true,
                  financeId: true,
                  userEmail: true,
                  accOrderId: true,
                  workOrderId: true,
                }
              },
            }
          },

          ServicesOnWorkOrders: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              quantity: true,
              hr: true,
              status: true,
              workOrderId: true,
              serviceId: true,
              service: {
                select: {
                  id: true,
                  createdAt: true,
                  updatedAt: true,
                  description: true,
                  estHr: true,
                  service: true,
                  price: true,
                }
              },
            }
          },

          Payments: {
            select: {
              id: true,
              createdAt: true,
              paymentType: true,
              cardType: true,
              amountPaid: true,
              cardNum: true,
              receiptId: true,
              financeId: true,
              userEmail: true,
              accOrderId: true,
              workOrderId: true,
            }
          },

          WorkOrderApts: {
            select: {
              id: true,
              tech: true,
              techEmail: true,
              writer: true,
              start: true,
              end: true,
              title: true,
              workOrderId: true,
              completed: true,
              resourceId: true,
              unit: true,
              mileage: true,
              vin: true,
              tag: true,
              motor: true,
              color: true,
              location: true,
              createdAt: true,
              updatedAt: true,
            }
          },
          WorkOrderClockEntries: {
            select: {
              id: true,
              start: true,
              end: true,
              userEmail: true,
              username: true,
              workOrderId: true,
              createdAt: true,
              updatedAt: true,

            }
          },
        },
      },
      Finance: {
        select: {
          // Finance fields
          id: true,
          financeManager: true,
          userEmail: true,
          userName: true,
          financeManagerName: true,
          email: true,
          firstName: true,
          lastName: true,
          phone: true,
          name: true,
          address: true,
          city: true,
          postal: true,
          province: true,
          dl: true,
          typeOfContact: true,
          timeToContact: true,
          dob: true,
          othTax: true,
          optionsTotal: true,
          lienPayout: true,
          leadNote: true,
          sendToFinanceNow: true,
          dealNumber: true,
          iRate: true,
          months: true,
          discount: true,
          total: true,
          onTax: true,
          on60: true,
          biweekly: true,
          weekly: true,
          weeklyOth: true,
          biweekOth: true,
          oth60: true,
          weeklyqc: true,
          biweeklyqc: true,
          qc60: true,
          deposit: true,
          biweeklNatWOptions: true,
          weeklylNatWOptions: true,
          nat60WOptions: true,
          weeklyOthWOptions: true,
          biweekOthWOptions: true,
          oth60WOptions: true,
          biweeklNat: true,
          weeklylNat: true,
          nat60: true,
          qcTax: true,
          otherTax: true,
          totalWithOptions: true,
          otherTaxWithOptions: true,
          desiredPayments: true,
          admin: true,
          commodity: true,
          pdi: true,
          discountPer: true,
          userLoanProt: true,
          userTireandRim: true,
          userGap: true,
          userExtWarr: true,
          userServicespkg: true,
          deliveryCharge: true,
          vinE: true,
          lifeDisability: true,
          rustProofing: true,
          userOther: true,
          referral: true,
          visited: true,
          bookedApt: true,
          aptShowed: true,
          aptNoShowed: true,
          testDrive: true,
          metService: true,
          metManager: true,
          metParts: true,
          sold: true,
          depositMade: true,
          refund: true,
          turnOver: true,
          financeApp: true,
          approved: true,
          signed: true,
          pickUpSet: true,
          demoed: true,
          lastContact: true,
          status: true,
          customerState: true,
          result: true,
          timesContacted: true,
          nextAppointment: true,
          followUpDay: true,
          deliveryDate: true,
          delivered: true,
          deliveredDate: true,
          notes: true,
          visits: true,
          progress: true,
          metSalesperson: true,
          metFinance: true,
          financeApplication: true,
          pickUpDate: true,
          pickUpTime: true,
          depositTakenDate: true,
          docsSigned: true,
          tradeRepairs: true,
          seenTrade: true,
          lastNote: true,
          applicationDone: true,
          licensingSent: true,
          liceningDone: true,
          refunded: true,
          cancelled: true,
          lost: true,
          dLCopy: true,
          insCopy: true,
          testDrForm: true,
          voidChq: true,
          loanOther: true,
          signBill: true,
          ucda: true,
          tradeInsp: true,
          customerWS: true,
          otherDocs: true,
          urgentFinanceNote: true,
          funded: true,
          leadSource: true,
          financeDeptProductsTotal: true,
          bank: true,
          loanNumber: true,
          idVerified: true,
          dealerCommission: true,
          financeCommission: true,
          salesCommission: true,
          firstPayment: true,
          loanMaturity: true,
          quoted: true,

          // Calls
          InPerson: true,
          Phone: true,
          SMS: true,
          Email: true,
          Other: true,

          // Relations
          financeStorage: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              url: true,
              filePath: true,
              financeId: true,
            }
          },
          clientApts: {
            select: {
              id: true,
              financeId: true,
              title: true,
              start: true,
              end: true,
              contactMethod: true,
              completed: true,
              apptStatus: true,
              apptType: true,
              note: true,
              unit: true,
              brand: true,
              firstName: true,
              lastName: true,
              email: true,
              phone: true,
              address: true,
              userEmail: true,
              userId: true,
              description: true,
              userName: true,
              attachments: true,
              direction: true,
              resultOfcall: true,
              resourceId: true,
              activixId: true,
              activixNoteId: true,
              createdAt: true,
              updatedAt: true,
              isPublished: true,
            }
          },
          Comm: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              userEmail: true,
              type: true,
              body: true,
              subject: true,
              userName: true,
              direction: true,
              result: true,
              financeId: true,
            },
          },
          FinanceDeptProducts: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              packageName: true,
              packagePrice: true,
              financeId: true,
            }
          },
          FinanceUnit: {
            select: {
              paintPrem: true,
              licensing: true,
              stockNum: true,
              options: true,
              accessories: true,
              freight: true,
              labour: true,
              year: true,
              brand: true,
              mileage: true,
              model: true,
              model1: true,
              color: true,
              modelCode: true,
              msrp: true,
              trim: true,
              vin: true,
              bikeStatus: true,
              invId: true,
              location: true,
              id: true,
              createdAt: true,
              updatedAt: true,
              financeId: true,
            }
          },
          FinanceTradeUnit: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              financeId: true,
              price: true,
              brand: true,
              model: true,
              color: true,
              accessories: true,
              options: true,
              year: true,
              vin: true,
              trim: true,
              mileage: true,
              location: true,
              condition: true,
              repairs: true,
              stockNum: true,
              licensing: true,
              tradeEval: true,
            }
          },
          AccOrders: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              userEmail: true,
              userName: true,
              dept: true,
              sellingDept: true,
              total: true,
              discount: true,
              discPer: true,
              paid: true,
              paidDate: true,
              status: true,
              workOrderId: true,
              note: true,
              financeId: true,
              clientfileId: true,

              AccHandoff: {
                select: {
                  id: true,
                  createdAt: true,
                  updatedAt: true,
                  sendTo: true,
                  handOffTime: true,
                  status: true,
                  sendToCompleted: true,
                  completedTime: true,
                  notes: true,
                  handOffDept: true,
                  AccOrderId: true,
                }
              },

              AccessoriesOnOrders: {
                select: {
                  id: true,
                  quantity: true,
                  accOrderId: true,
                  status: true,
                  orderNumber: true,
                  OrderInvId: true,
                  accessoryId: true,
                  service: true,
                  hour: true,

                  accessory: {
                    select: {
                      id: true,
                      createdAt: true,
                      updatedAt: true,
                      partNumber: true,
                      brand: true,
                      name: true,
                      price: true,
                      cost: true,
                      quantity: true,
                      minQuantity: true,
                      description: true,
                      category: true,
                      subCategory: true,
                      onOrder: true,
                      distributer: true,
                      location: true,
                      note: true,
                      workOrderSuggestion: true,
                    }
                  }
                }
              },

              Payments: {
                select: {
                  id: true,
                  createdAt: true,
                  paymentType: true,
                  cardType: true,
                  amountPaid: true,
                  cardNum: true,
                  receiptId: true,
                  financeId: true,
                  userEmail: true,
                  accOrderId: true,
                  workOrderId: true,
                }
              },
            },
          },
          WorkOrders: {
            select: {
              workOrderId: true,
              unit: true,
              mileage: true,
              vin: true,
              tag: true,
              motor: true,
              color: true,
              budget: true,
              waiter: true,
              totalLabour: true,
              totalParts: true,
              subTotal: true,
              total: true,
              writer: true,
              userEmail: true,
              tech: true,
              techEmail: true,
              notes: true,
              customerSig: true,
              status: true,
              location: true,
              quoted: true,
              paid: true,
              remaining: true,
              FinanceUnitId: true,
              ServiceUnitId: true,
              financeId: true,
              clientfileId: true,
              note: true,
              closedAt: true,
              createdAt: true,
              updatedAt: true,

              FinanceUnit: {
                select: {
                  paintPrem: true,
                  licensing: true,
                  stockNum: true,
                  options: true,
                  accessories: true,
                  freight: true,
                  labour: true,
                  year: true,
                  brand: true,
                  mileage: true,
                  model: true,
                  model1: true,
                  color: true,
                  modelCode: true,
                  msrp: true,
                  trim: true,
                  vin: true,
                  bikeStatus: true,
                  invId: true,
                  location: true,
                  id: true,
                  createdAt: true,
                  updatedAt: true,
                  financeId: true,
                }
              },

              ServiceUnit: {
                select: {
                  id: true,
                  createdAt: true,
                  updatedAt: true,
                  price: true,
                  brand: true,
                  model: true,
                  color: true,
                  accessories: true,
                  options: true,
                  year: true,
                  vin: true,
                  trim: true,
                  mileage: true,
                  location: true,
                  condition: true,
                  repairs: true,
                  stockNum: true,
                  motor: true,
                  tag: true,
                  licensing: true,
                  tradeEval: true,
                  clientfileId: true,
                }
              },

              AccOrders: {
                select: {
                  id: true,
                  createdAt: true,
                  updatedAt: true,
                  userEmail: true,
                  userName: true,
                  dept: true,
                  sellingDept: true,
                  total: true,
                  discount: true,
                  discPer: true,
                  paid: true,
                  paidDate: true,
                  status: true,
                  workOrderId: true,
                  note: true,
                  financeId: true,
                  clientfileId: true,
                  AccessoriesOnOrders: {
                    select: {
                      id: true,
                      quantity: true,
                      accOrderId: true,
                      status: true,
                      orderNumber: true,
                      OrderInvId: true,
                      accessoryId: true,
                      service: true,
                      hour: true,
                    }
                  },
                  Payments: {
                    select: {
                      id: true,
                      createdAt: true,
                      paymentType: true,
                      cardType: true,
                      amountPaid: true,
                      cardNum: true,
                      receiptId: true,
                      financeId: true,
                      userEmail: true,
                      accOrderId: true,
                      workOrderId: true,
                    }
                  },
                }
              },

              ServicesOnWorkOrders: {
                select: {
                  id: true,
                  createdAt: true,
                  updatedAt: true,
                  quantity: true,
                  hr: true,
                  status: true,
                  workOrderId: true,
                  serviceId: true,
                  service: {
                    select: {
                      id: true,
                      createdAt: true,
                      updatedAt: true,
                      description: true,
                      estHr: true,
                      service: true,
                      price: true,
                    }
                  },
                }
              },

              Payments: {
                select: {
                  id: true,
                  createdAt: true,
                  paymentType: true,
                  cardType: true,
                  amountPaid: true,
                  cardNum: true,
                  receiptId: true,
                  financeId: true,
                  userEmail: true,
                  accOrderId: true,
                  workOrderId: true,
                }
              },

              WorkOrderApts: {
                select: {
                  id: true,
                  tech: true,
                  techEmail: true,
                  writer: true,
                  start: true,
                  end: true,
                  title: true,
                  workOrderId: true,
                  completed: true,
                  resourceId: true,
                  unit: true,
                  mileage: true,
                  vin: true,
                  tag: true,
                  motor: true,
                  color: true,
                  location: true,
                  createdAt: true,
                  updatedAt: true,
                }
              },
              WorkOrderClockEntries: {
                select: {
                  id: true,
                  start: true,
                  end: true,
                  userEmail: true,
                  username: true,
                  workOrderId: true,
                  createdAt: true,
                  updatedAt: true,

                }
              },
            },
          },
          Payments: {
            select: {
              id: true,
              createdAt: true,
              paymentType: true,
              cardType: true,
              amountPaid: true,
              cardNum: true,
              receiptId: true,
              financeId: true,
              userEmail: true,
              accOrderId: true,
              workOrderId: true,
            }
          },
          FinanceNote: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              body: true,
              userEmail: true,
              userName: true,
              clientfileId: true,
              financeId: true,
            }
          },
        }
      },

    }
  });
  console.log(users, 'clientfiles api')
  return json({ users });
};
