import { createReadableStreamFromReadable } from '@remix-run/node';
import { Readable } from 'node:stream';
import { prisma } from '~/libs';

export const loader = async () => {
  const data = await prisma.inventoryMotorcycle.findMany();

  const headers = [
    "packageNumber",
    "packagePrice",
    "stockNumber",
    "type",
    "class",
    "year",
    "make",
    "model",
    "modelName",
    "submodel",
    "subSubmodel",
    "price",
    "exteriorColor",
    "mileage",
    "consignment",
    "onOrder",
    "expectedOn",
    "status",
    "orderStatus",
    "hdcFONumber",
    "hdmcFONumber",
    "vin",
    "age",
    "floorPlanDueDate",
    "location",
    "stocked",
    "stockedDate",
    "isNew",
    "actualCost",
    "mfgSerialNumber",
    "engineNumber",
    "plates",
    "keyNumber",
    "length",
    "width",
    "engine",
    "fuelType",
    "power",
    "chassisNumber",
    "chassisYear",
    "chassisMake",
    "chassisModel",
    "chassisType",
    "registrationState",
    "registrationExpiry",
    "grossWeight",
    "netWeight",
    "insuranceCompany",
    "policyNumber",
    "insuranceAgent",
    "insuranceStartDate",
    "insuranceEndDate",
    "sold",
  ];

  const testData = {
    "packageNumber": '165265',
    "packagePrice": '350',
    "stockNumber": 'B8858',
    "type": 'H-D Large Cruiser',
    "class": '',
    "year": '2024',
    "make": 'H-D',
    "model": 'CVO Road Glide',
    "modelName": 'FLHXSE CVO',
    "submodel": '',
    "subSubmodel": '',
    "price": '62000',
    "exteriorColor": 'Black',
    "mileage": '2',
    "consignment": false,
    "onOrder": false,
    "expectedOn": '',
    "status": '',
    "orderStatus": '',
    "hdcFONumber": '',
    "hdmcFONumber": '',
    "vin": 'B654648151',
    "age": 45,
    "floorPlanDueDate": '',
    "location": 'Floor',
    "stocked": true,
    "stockedDate": 'Jan 5th 2024',
    "isNew": true,
    "actualCost": '',
    "mfgSerialNumber": '',
    "engineNumber": '',
    "plates": '',
    "keyNumber": '',
    "length": '',
    "width": '',
    "engine": '',
    "fuelType": '',
    "power": '',
    "chassisNumber": '',
    "chassisYear": '',
    "chassisMake": '',
    "chassisModel": '',
    "chassisType": '',
    "registrationState": '',
    "registrationExpiry": '',
    "grossWeight": '',
    "netWeight": '',
    "insuranceCompany": '',
    "policyNumber": '',
    "insuranceAgent": '',
    "insuranceStartDate": '',
    "insuranceEndDate": '',
    "sold": false,
    "freight": 750.85
  }
  const csvData = data.length > 0 ? data : [testData];
  const rows = csvData.map(entry => [
    entry.packageNumber,
    entry.packagePrice,
    entry.stockNumber,
    entry.type,
    entry.class,
    entry.year,
    entry.make,
    entry.model,
    entry.modelName,
    entry.submodel,
    entry.subSubmodel,
    entry.price,
    entry.exteriorColor,
    entry.mileage,
    entry.consignment,
    entry.onOrder,
    entry.expectedOn,
    entry.status,
    entry.orderStatus,
    entry.hdcFONumber,
    entry.hdmcFONumber,
    entry.vin,
    entry.age,
    entry.floorPlanDueDate,
    entry.location,
    entry.stocked,
    entry.stockedDate,
    entry.isNew,
    entry.actualCost,
    entry.mfgSerialNumber,
    entry.engineNumber,
    entry.plates,
    entry.keyNumber,
    entry.length,
    entry.width,
    entry.engine,
    entry.fuelType,
    entry.power,
    entry.chassisNumber,
    entry.chassisYear,
    entry.chassisMake,
    entry.chassisModel,
    entry.chassisType,
    entry.registrationState,
    entry.registrationExpiry,
    entry.grossWeight,
    entry.netWeight,
    entry.insuranceCompany,
    entry.policyNumber,
    entry.insuranceAgent,
    entry.insuranceStartDate,
    entry.insuranceEndDate,
    entry.sold,

  ].map(value => (value === null ? '' : value)).join(','));

  const csvContent = [headers.join(','), ...rows].join('\n');

  const file = createReadableStreamFromReadable(
    Readable.from([csvContent]),
  );

  // Return the response with appropriate headers for downloading the CSV file
  return new Response(file, {
    headers: {
      'Content-Disposition': 'attachment; filename="UnitInventory.csv"',
      'Content-Type': 'text/csv',
    },
  });
};
