export const ListOptionsCanAmSXS = () => (
    <datalist id="ListOptions">
        <option value="defender hd7 tundra green 0006xpb00" />
        <option value="defender dps hd7 tundra green 0008wpb00" />
        <option value="defender dps hd7 mossy oak break-up country camo 0008wpd00" />
        <option value="defender hd9 tundra green 0006wpb00" />
        <option value="defender dps hd9 tundra green 0008epb00" />
        <option value="defender dps hd9 oxford blue 0008epd00" />
        <option value="defender dps hd9 timeless black 0008epf00" />
        <option value="defender dps hd9 mossy oak break-up country camo 0008eph00" />
        <option value="defender xt hd9 oxford blue 0008fpb00" />
        <option value="defender xt hd9 stone gray 0008fpd00" />
        <option value="defender xt hd9 timeless black 0008fpf00" />
        <option value="defender xt hd9 mossy oak break-up country camo 0008fph00" />
        <option value="defender dps cab hd9 tundra green 0008upb00" />
        <option value="defender dps hd10 tundra green 0008bpb00" />
        <option value="defender dps hd10 oxford blue 0008bpd00" />
        <option value="defender dps hd10 timeless black 0008bpf00" />
        <option value="defender xt hd10 oxford blue 0008cpb00" />
        <option value="defender xt hd10 stone gray 0008cpd00" />
        <option value="defender xt hd10 timeless black 0008cpf00" />
        <option value="defender xt hd10 mossy oak break-up country camo 0008cph00" />
        <option value="defender x mr hd10 liquid titanium & magma red 0008ypb00" />
        <option value="defender x mr hd10 mossy oak break-up country camo 0008ypc00" />
        <option value="defender x mr hd10 with half doors liquid titanium & magma red 0008ypa00" />
        <option value="defender limited cab hd10 oxford blue 0008jpb00" />
        <option value="defender limited cab hd10 stone gray 0008jpd00" />
        <option value="defender limited cab hd10 desert tan & timeless black 0008jph00" />
        <option value="defender limited cab hd10 mossy oak break-up country camo 0008jpf00" />
        <option value="defender max hd7 tundra green 0008zpb00" />
        <option value="defender max hd9 tundra green 0008dpb00" />
        <option value="defender max dps hd7 tundra green 0008ppd00" />
        <option value="defender max dps hd9 tundra green 0008rpb00" />
        <option value="defender max dps hd9 timeless black 0008rpd00" />
        <option value="defender max dps hd9 mossy oak break-up country camo 0008rpf00" />
        <option value="defender max xt hd9 oxford blue 0008spb00" />
        <option value="defender max xt hd9 stone gray 0008spd00" />
        <option value="defender max xt hd9 mossy oak break-up country camo 0008spf00" />
        <option value="defender max dps hd10 oxford blue 0008lpb00" />
        <option value="defender max dps hd10 timeless black 0008lpd00" />
        <option value="defender max xt hd10 oxford blue 0008mpb00" />
        <option value="defender max xt hd10 stone gray 0008mpd00" />
        <option value="defender max xt hd10 mossy oak break-up country camo 0008mpf00" />
        <option value="defender max lone star hd10 night black 0006upa00" />
        <option value="defender max x mr mossy oak break-up country camo 0008ppb00" />
        <option value="defender max x mr with half doors liquid titanium & magma red 0008ppa00" />
        <option value="defender max limited cab hd10 oxford blue 0006mpb00" />
        <option value="defender max limited cab hd10 stone gray 0006mpd00" />
        <option value="defender max limited cab hd10 desert tan & timeless black 0006mph00" />
        <option value="defender max limited cab hd10 mossy oak break-up country camo 0006mpf00" />
        <option value="defender max lone star cab hd10 night black 0006lpa00" />
        <option value="defender pro dps hd10 tundra green 0006apb00" />
        <option value="defender pro xt hd10 timeless black 0006epd00" />
        <option value="defender pro limited cab hd10 stone gray 0009hpd00" />
        <option value="defender 6x6 dps hd10 tundra green 0009vpa00" />
        <option value="defender 6x6 xt hd10 oxford blue 0009rpa00" />
        <option value="defender 6x6 limited cab hd10 oxford blue 0009spa00" />
        <option value="commander dps 700 tundra green 0009ppb00" />
        <option value="commander xt 700 oxford blue 0009apb00" />
        <option value="commander xt 700 triple black 0009apd00" />
        <option value="commander dps 1000r tundra green 0006ppb00" />
        <option value="commander xt 1000r oxford blue 0006gpb00" />
        <option value="commander xt 1000r triple black 0006gpd00" />
        <option value="commander xt 1000r mossy oak break-up country camo 0006gpf00" />
        <option value="commander x mr 1000r mossy oak break-up country camo 0006spa00" />
        <option value="commander xt-p 1000r desert tan & carbon black 0006ypb00" />
        <option value="commander max dps 1000r tundra green 0006hpb00" />
        <option value="commander max xt 1000r oxford blue 0006kpb00" />
        <option value="commander max xt 1000r triple black 0006kpd00" />
        <option value="commander max xt 1000r mossy oak break-up country camo 0006kpf00" />
        <option value="commander max xt-p 1000r desert tan & carbon black 0006cpb00" />
        <option value="maverick trail 700 catalyst gray 0007rpb00" />
        <option value="maverick trail dps 700 triple black 0007hpb00" />
        <option value="maverick trail dps 1000 triple black 0007fpf00" />
        <option value="maverick trail dps 1000 oxford blue 0007fpb00" />
        <option value="maverick trail dps 1000 mossy oak break-up country camo 0007fpd00" />
        <option value="maverick sport dps 1000r oxford blue 0009gpb00" />
        <option value="maverick sport dps 1000r triple black 0009gpd00" />
        <option value="maverick sport x xc 1000r desert tan & carbon black 0007cpb00" />
        <option value="maverick sport x mr 1000r liquid titanium & magma red 0006fpa00" />
        <option value="maverick sport x rc 1000r mineral gray & desert tan 0007bpb00" />
        <option value="maverick sport max dps 1000r triple black 0009jpb00" />
        <option value="maverick x3 ds turbo catalyst gray 0009dph00" />
        <option value="maverick x3 ds turbo octane blue 0009dpb00" />
        <option value="maverick x3 ds turbo desert tan & carbon black 0009dpf00" />
        <option value="maverick x3 ds turbo rr catalyst gray 0007xpf00" />
        <option value="maverick x3 ds turbo rr octane blue 0007xpb00" />
        <option value="maverick x3 ds turbo rr desert tan & carbon black 0007xpd00" />
        <option value="maverick x3 rs turbo rr catalyst gray 0009epf00" />
        <option value="maverick x3 rs turbo rr octane blue 0009epb00" />
        <option value="maverick x3 rs turbo rr desert tan & carbon black 0009epd00" />
        <option value="maverick x3 x ds turbo rr triple black 0007spf00" />
        <option value="maverick x3 x ds turbo rr desert tan, carbon black & magma red 0007spb00" />
        <option value="maverick x3 x rs turbo rr triple black 0007tpf00" />
        <option value="maverick x3 x rs turbo rr desert tan, carbon black & magma red 0007tpb00" />
        <option value="maverick x3 x rs turbo rr intense blue, carbon black & chalk gray 0007tpk00" />
        <option value="maverick x3 x rs turbo rr smart-shox triple black 0007tph00" />
        <option value="maverick x3 x rs turbo rr smart-shox desert tan, carbon black & magma red 0007tpd00" />
        <option value="maverick x3 x rs turbo rr smart-shox intense blue, carbon black & chalk gray 0007tpm00" />
        <option value="maverick x3 x mr 64'' turbo rr liquid titanium & magma red 0006vpa00" />
        <option value="maverick x3 x mr turbo rr liquid titanium & magma red 0009lpa00" />
        <option value="maverick x3 x rc 64'' turbo rr mineral gray & desert tan 0007kpb00" />
        <option value="maverick x3 x rc turbo rr mineral gray & desert tan 0009mpb00" />
        <option value="maverick x3 max ds turbo catalyst gray 0007wph00" />
        <option value="maverick x3 max ds turbo octane blue 0007wpb00" />
        <option value="maverick x3 max ds turbo desert tan & carbon black 0007wpf00" />
        <option value="maverick x3 max ds turbo rr catalyst gray 0007upf00" />
        <option value="maverick x3 max ds turbo rr octane blue 0007upb00" />
        <option value="maverick x3 max ds turbo rr desert tan & carbon black 0007upd00" />
        <option value="maverick x3 max rs turbo rr catalyst gray 0007ypf00" />
        <option value="maverick x3 max rs turbo rr octane blue 0007ypb00" />
        <option value="maverick x3 max rs turbo rr desert tan & carbon black 0007ypd00" />
        <option value="maverick x3 max x ds turbo rr triple black 0007vpf00" />
        <option value="maverick x3 max x ds turbo rr desert tan, carbon black & magma red 0007vpb00" />
        <option value="maverick x3 max x rs turbo rr triple black 0009npf00" />
        <option value="maverick x3 max x rs turbo rr desert tan, carbon black & magma red 0009npb00" />
        <option value="maverick x3 max x rs turbo rr intense blue, carbon black & chalk gray 0009npk00" />
        <option value="maverick x3 max x rs turbo rr smart-shox triple black 0009nph00" />
        <option value="maverick x3 max x rs turbo rr smart-shox desert tan, carbon black & magma red 0009npd00" />
        <option value="maverick x3 max x rs turbo rr smart-shox intense blue, carbon black & chalk gray 0009npm00" />
        <option value="maverick x3 max x mr turbo rr liquid titanium & magma red 0007zpa00" />
    </datalist>
)

