
export const SkidooList = () => (
	<datalist id="ListOptions">
		<option value="mxz adr w blizzard pkg 129 850 e-tec ice ripper xt 1.25 e.s. black udra" />
		<option value="mxz adr w blizzard pkg 129 850 e-tec ice ripper xt 1.25 e.s. catalyst grey udrb" />
		<option value="mxz adr w blizzard pkg 137 850 e-tec ice ripper xt 1.25 e.s. black udrc" />
		<option value="mxz adr w blizzard pkg 137 850 e-tec ice ripper xt 1.25 e.s. catalyst grey udrd" />
		<option value="mxz adr w blizzard pkg 129 600r e-tec ice ripper xt 1.25 e.s. black uera" />
		<option value="mxz adr w blizzard pkg 129 600r e-tec ice ripper xt 1.25 e.s. catalyst grey uerb" />
		<option value="mxz adr w blizzard pkg 137 600r e-tec ice ripper xt 1.25 e.s. black uerc" />
		<option value="mxz adr w blizzard pkg 137 600r e-tec ice ripper xt 1.25 e.s. catalyst grey uerd" />
		<option value="mxz adrenaline 129 850 e-tec ripsaw 1.25 e.s. black bdrf" />
		<option value="mxz adrenaline 129 850 e-tec ripsaw 1.25 e.s. neo yellow bdre" />
		<option value="mxz adrenaline 137 850 e-tec ripsaw 1.25 e.s. black bdrh" />
		<option value="mxz adrenaline 137 850 e-tec ripsaw 1.25 e.s. neo yellow bdrg" />
		<option value="mxz adrenaline 129 600r e-tec ripsaw 1.25 e.s. black bdrb" />
		<option value="mxz adrenaline 129 600r e-tec ripsaw 1.25 e.s. neo yellow bdra" />
		<option value="mxz adrenaline 137 600r e-tec ripsaw 1.25 e.s. black bdrd" />
		<option value="mxz adrenaline 137 600r e-tec ripsaw 1.25 e.s. neo yellow bdrc" />
		<option value="mxz sport 129 600 efi ripsaw 1.25 e.s. neo yellow bhrc" />
		<option value="mxz sport 137 600 efi ripsaw 1.25 e.s. neo yellow bhrb" />
		<option value="mxz neo+ 600 efi (55) ripsaw 1.25 e.s. neo yellow  black bpra" />
		<option value="mxz neo 600 efi (40) cobra 1.0 e.s. neo yellow  catalyst grey bbra" />
		<option value="mxz 200 neo yellow ywrb" />
		<option value="mxz 120 neo yellow ywra" />
		<option value="renegade adr w enduro pkg 850 e-tec ice ripper xt 1.25 e.s. w 10.25 touchscreen black  neo yellow urra" />
		<option value="renegade adr w enduro pkg 600r e-tec ice ripper xt 1.25 e.s. w 10.25 touchscreen black  neo yellow usra" />
		<option value="renegade adr w enduro pkg 900 ace turbo r ice ripper xt 1.25 e.s. w 10.25 touchscreen black  neo yellow dpra" />
		<option value="renegade adr w enduro pkg 900 ace turbo ice ripper xt 1.25 e.s. w 10.25 touchscreen black  neo yellow drra" />
		<option value="renegade adr w enduro pkg 900 ace ice ripper xt 1.25 e.s. w 10.25 touchscreen black  neo yellow unra" />
		<option value="renegade adrenaline 900 ace turbo r ripsaw 1.25 e.s. black dtrb" />
		<option value="renegade adrenaline 900 ace turbo r ripsaw 1.25 e.s. neo yellow dtra" />
		<option value="renegade adrenaline 900 ace turbo ripsaw 1.25 e.s. black durb" />
		<option value="renegade adrenaline 900 ace turbo ripsaw 1.25 e.s. neo yellow dura" />
		<option value="renegade adrenaline 900 ace ripsaw 1.25 e.s. black mbrb" />
		<option value="renegade adrenaline 900 ace ripsaw 1.25 e.s. neo yellow mbra" />
		<option value="renegade sport 600 ace ripsaw 1.25 e.s. neo yellow mcra" />
		<option value="grand touring le w luxury pkg 900 ace turbo r silent ice track ii 1.25 e.s. w 10.25 touchscreen terra green eprb" />
		<option value="grand touring le w luxury pkg 900 ace turbo silent ice track ii 1.25 e.s. w 10.25 touchscreen terra green errb" />
		<option value="grand touring le w luxury pkg 900 ace silent ice track ii 1.25 e.s. w 10.25 touchscreen terra green ebrb" />
		<option value="grand touring le 900 ace turbo r silent track ii 1.25 e.s. black epra" />
		<option value="grand touring le 900 ace turbo silent track ii 1.25 e.s. black erra" />
		<option value="grand touring le 900 ace silent track ii 1.25 e.s. black ebra" />
		<option value="grand touring sport 900 ace silent track ii 1.25 e.s. neo yellow eara" />
		<option value="grand touring sport 600 ace silent track ii 1.25 e.s. neo yellow etra" />
		<option value="backcountry adrenaline 850 e-tec cobra 1.6 e.s. black ugra" />
		<option value="backcountry adrenaline 850 e-tec powdermax 2.0 e.s. black ugrb" />
		<option value="backcountry adrenaline 850 e-tec cobra 1.6 e.s. neo yellow ugrc" />
		<option value="backcountry adrenaline 850 e-tec powdermax 2.0 e.s. neo yellow ugrd" />
		<option value="backcountry adrenaline 600r e-tec cobra 1.6 e.s. black ujra" />
		<option value="backcountry adrenaline 600r e-tec powdermax 2.0 e.s. black ujrb" />
		<option value="backcountry adrenaline 600r e-tec cobra 1.6 e.s. neo yellow ujrc" />
		<option value="backcountry adrenaline 600r e-tec powdermax 2.0 e.s. neo yellow ujrd" />
		<option value="backcountry sport 600 efi cobra 1.6 e.s. neo yellow ubra" />
		<option value="backcountry sport 600 efi powdermax 2.0 e.s. neo yellow ubrb" />
		<option value="expedition le 20 900 ace turbo r silent cobra 1.5 e.s. black awra" />
		<option value="expedition le 20 900 ace turbo r silent cobra 1.5 e.s. arctic desert awrb" />
		<option value="expedition le 20 900 ace turbo silent cobra 1.5 e.s. black acra" />
		<option value="expedition le 20 900 ace turbo silent cobra 1.5 e.s. arctic desert acrb" />
		<option value="expedition le 20 900 ace silent cobra 1.5 e.s. black aara" />
		<option value="expedition le 20 900 ace silent cobra 1.5 e.s. (same as aara) black aard" />
		<option value="expedition le 20 900 ace silent cobra 1.5 e.s. arctic desert aarb" />
		<option value="expedition le 20 600r e-tec silent cobra 1.5 e.s. black abra" />
		<option value="expedition le 20 600r e-tec silent cobra 1.5 e.s. arctic desert abrb" />
		<option value="expedition le 24 900 ace turbo r silent cobra 1.5 e.s. black axra" />
		<option value="expedition le 24 900 ace turbo r silent cobra 1.5 e.s. arctic desert axrb" />
		<option value="expedition le 24 900 ace turbo silent cobra 1.5 e.s. black asra" />
		<option value="expedition le 24 900 ace turbo silent cobra 1.5 e.s. arctic desert asrb" />
		<option value="expedition le 24 900 ace silent cobra 1.5 e.s. black arra" />
		<option value="expedition le 24 900 ace silent cobra 1.5 e.s. (same as arra) black arrd" />
		<option value="expedition le 24 900 ace silent cobra 1.5 e.s. arctic desert arrb" />
		<option value="expedition le 24 600r e-tec silent cobra 1.5 e.s. black amra" />
		<option value="expedition le 24 600r e-tec silent cobra 1.5 e.s. arctic desert amrb" />
		<option value="expedition xtreme 900 ace turbo r cobra 1.8 e.s. black aprd" />
		<option value="expedition xtreme 900 ace turbo r cobra 1.8 e.s. neo mint aprb" />
		<option value="expedition xtreme 850 e-tec cobra 1.8 e.s. black adrd" />
		<option value="expedition xtreme 850 e-tec cobra 1.8 e.s. neo mint adrb" />
		<option value="expedition sport 900 ace charger 1.5 e.s. neo yellow kdra" />
		<option value="expedition sport 600 ace charger 1.5 e.s. neo yellow kcra" />
		<option value="expedition sport 600 efi charger 1.5 e.s. neo yellow kara" />
		<option value="skandic le 20 900 ace silent cobra 1.5 e.s. black ahra" />
		<option value="skandic le 20 900 ace silent cobra 1.5 e.s. (same as ahra) black ahrd" />
		<option value="skandic le 20 900 ace silent cobra 1.5 e.s. arctic desert ahrb" />
		<option value="skandic le 20 600 ace silent cobra 1.5 e.s. black akra" />
		<option value="skandic le 20 600 ace silent cobra 1.5 e.s. arctic desert akrb" />
		<option value="skandic le 20 600r e-tec silent cobra 1.5 e.s. black alra" />
		<option value="skandic le 20 600r e-tec silent cobra 1.5 e.s. arctic desert alrb" />
		<option value="skandic le 20 600 efi silent cobra 1.5 e.s. black atrd" />
		<option value="skandic le 20 600 efi silent cobra 1.5 e.s. arctic desert atrb" />
		<option value="skandic le 24 900 ace silent cobra 1.5 e.s. black anra" />
		<option value="skandic le 24 900 ace silent cobra 1.5 e.s. (same as anra) black anrh" />
		<option value="skandic le 24 900 ace silent cobra 1.5 e.s. arctic desert anrb" />
		<option value="skandic le 24 600r e-tec silent cobra 1.5 e.s. black aura" />
		<option value="skandic le 24 600r e-tec silent cobra 1.5 e.s. arctic desert aurb" />
		<option value="skandic sport 600 efi utility 1.25 e.s. neo yellow ajra" />
		<option value="tundra le 600 ace charger 1.5 e.s. black gnra" />
		<option value="tundra le 600 efi charger 1.5 e.s. black gdra" />
		<option value="tundra le 600 efi charger 1.5 e.s. (same as gdra) black gdrc" />
		<option value="tundra sport 600 ace cobra 1.6 e.s. neo yellow gmra" />
		<option value="tundra sport 600 efi cobra 1.6 e.s. neo yellow gkra" />
		<option value="summit - high-altidude calibration only, except neo/neo+" />
		<option value="summit adr w edge pkg 146 850 e-tec powdermax flexedge 2.5 shot arctic desert ckrd" />
		<option value="summit adr w edge pkg 146 850 e-tec powdermax flexedge 2.5 shot timeless black ckrc" />
		<option value="summit adr w edge pkg 154 850 e-tec powdermax light flexedge 2.5 shot arctic desert cgrc" />
		<option value="summit adr w edge pkg 154 850 e-tec powdermax x-light flexedge 3.0 shot arctic desert cgrd" />
		<option value="summit adr w edge pkg 154 850 e-tec powdermax light flexedge 2.5 shot timeless black cgra" />
		<option value="summit adr w edge pkg 154 850 e-tec powdermax x-light flexedge 3.0 shot timeless black cgrb" />
		<option value="summit adr w edge pkg 165 850 e-tec powdermax x-light flexedge 3.0 shot arctic desert chrb" />
		<option value="summit adr w edge pkg 165 850 e-tec powdermax x-light flexedge 3.0 shot timeless black chra" />
		<option value="summit adr w edge pkg 146 600r e-tec powdermax flexedge 2.5 shot arctic desert ckrb" />
		<option value="summit adr w edge pkg 146 600r e-tec powdermax flexedge 2.5 shot timeless black ckra" />
		<option value="summit adr w edge pkg 154 600r e-tec powdermax light flexedge 2.5 shot arctic desert cgrh" />
		<option value="summit adr w edge pkg 154 600r e-tec powdermax light flexedge 2.5 shot timeless black cgrg" />
		<option value="summit adrenaline 146 850 e-tec powdermax flexedge 2.5 m.s. catalyst grey cdrf" />
		<option value="summit adrenaline 146 850 e-tec powdermax flexedge 2.5 e.s. catalyst grey cdre" />
		<option value="summit adrenaline 146 850 e-tec powdermax flexedge 2.5 shot catalyst grey cdrg" />
		<option value="summit adrenaline 146 850 e-tec powdermax flexedge 2.5 e.s. timeless black cdrh" />
		<option value="summit adrenaline 146 850 e-tec powdermax flexedge 2.5 shot timeless black cdrj" />
		<option value="summit adrenaline 154 850 e-tec powdermax light flexedge 2.5 m.s. catalyst grey cerh" />
		<option value="summit adrenaline 154 850 e-tec powdermax light flexedge 2.5 e.s. catalyst grey cerg" />
		<option value="summit adrenaline 154 850 e-tec powdermax light flexedge 2.5 shot catalyst grey cerf" />
		<option value="summit adrenaline 154 850 e-tec powdermax light flexedge 2.5 e.s. timeless black cerj" />
		<option value="summit adrenaline 154 850 e-tec powdermax light flexedge 2.5 shot timeless black cerk" />
		<option value="summit adrenaline 146 600r e-tec powdermax flexedge 2.5 m.s. catalyst grey cdrb" />
		<option value="summit adrenaline 146 600r e-tec powdermax flexedge 2.5 e.s. catalyst grey cdra" />
		<option value="summit adrenaline 146 600r e-tec powdermax flexedge 2.5 shot catalyst grey cdrk" />
		<option value="summit adrenaline 146 600r e-tec powdermax flexedge 2.5 e.s. timeless black cdrc" />
		<option value="summit adrenaline 146 600r e-tec powdermax flexedge 2.5 shot timeless black cdrd" />
		<option value="summit adrenaline 154 600r e-tec powdermax light flexedge 2.5 m.s. catalyst grey cerd" />
		<option value="summit adrenaline 154 600r e-tec powdermax light flexedge 2.5 e.s. catalyst grey cerc" />
		<option value="summit adrenaline 154 600r e-tec powdermax light flexedge 2.5 shot catalyst grey cere" />
		<option value="summit adrenaline 154 600r e-tec powdermax light flexedge 2.5 e.s. timeless black cera" />
		<option value="summit adrenaline 154 600r e-tec powdermax light flexedge 2.5 shot timeless black cerb" />
		<option value="summit neo+ 600 efi (55) hurricane flexedge 1.75 e.s. lac neo yellow  black tvra" />
		<option value="summit neo 600 efi (40) cobra flexedge 1.6 e.s. lac neo yellow  catalyst grey tura" />
	</datalist>
)
