export const HarleyList = () => (
    <datalist id="ListOptions2">
        <option value="model" />
        <option value="Nightster - Vivid Black - RH975" />
        <option value="Nightster - Color - RH975" />
        <option value="Nightster Special - Vivid Black - RH9755" />
        <option value="Nightster Special - Color - RH9755" />
        <option value="Sportster S - Vivid Black - RH1250S" />
        <option value="Sportster S - Color - RH1250S" />
        <option value="Softail Standard - FXST" />
        <option value="Street Bob 114 - Vivid Black - FXBBS" />
        <option value="Street Bob 114 - Color - FXBBS" />
        <option value="Fat Bob 114 - Vivid Black - FXFBS" />
        <option value="Fat Bob 114 -Color - FXFBS" />
        <option value="Low Rider S - Vivid Black - FXLRS" />
        <option value="Low Rider S - Color - FXLRS" />
        <option value="Low Rider ST - Vivid Black - FXLRST" />
        <option value="Low Rider ST - Color - FXLRST" />
        <option value="Low Rider ST - 2 Tone - FXLRST" />
        <option value="Fat Boy 114 - Vivid Black - FLFBS" />
        <option value="Fat Boy 114 - Color - FLFBS" />
        <option value="Fat Boy 114 - 2 Tone - FLFBS" />
        <option value="Breakout 117 - Vivid Black - FXBR" />
        <option value="Breakout 117 - Color - FXBR" />
        <option value="Heritage Classic  - Vivid Black - FLHCS" />
        <option value="Heritage Classic  - Color - FLHCS" />
        <option value="Heritage Classic  - 2 Tone - FLHCS" />
        <option value="Heritage Classic - 120th Ann - FLHCS" />
        <option value="Heritage Classic - Vivid Black w/ Black Finish - FLHCS" />
        <option value="Heritage Classic -Colour w/ Black Finish - FLHCS" />
        <option value="Heritage Classic - 2 Tone w/ Black Finish - FLHCS" />
        <option value="Pan America 1250 - RA1250" />
        <option value="Pan America 1250 Special  - Vivid Black - RA1250S" />
        <option value="Pan America 1250 Special  - Color - RA1250S" />
        <option value="Pan America 1250 Special - Two Tone - RA1250S" />
        <option value="Pan America 1250 Special - Vivid Black w/ Laced Wheels - RA1250S" />
        <option value="Pan America 1250 Special  - Color w/ Laced Wheels - RA1250S" />
        <option value="Pan America 1250 Special - Two Tone w/ Laced Wheels - RA1250S" />
        <option value="Street Glide - Vivid Black - FLHX" />
        <option value="Street Glide - Color - FLHX" />
        <option value="Road Glide - Vivid Black - FLTRX" />
        <option value="Road Glide - Color - FLTRX" />
        <option value="Road King Special - Vivid Black - FLTRXS" />
        <option value="Road King Special - Color - FLTRXS" />
        <option value="Electra Glide Highway King - Custom 2 Tone - FLHFB" />
        <option value="Street Glide Special - Vivid Black - FLHXS" />
        <option value="Street Glide Special - Color - FLHXS" />
        <option value="Street Glide Special - 2 Tone - FLHXS" />
        <option value="Street Glide Special - Vivid Black w/ Black Finish - FLHXS" />
        <option value="Street Glide Special -  Color  w/ Black Finish - FLHXS" />
        <option value="Street Glide Special -  2 Tone w/ Black Finish - FLHXS" />
        <option value="Street Glide Special - 120th Ann w/ Black Finish - FLHXS" />
        <option value="Road Glide Special - Vivid Black - FLTRXS" />
        <option value="Road Glide Special - Color - FLTRXS" />
        <option value="Road Glide Special - Vivid Black w/ Black Finish - FLTRXS" />
        <option value="Road Glide Special -  Color  w/ Black Finish - FLTRXS" />
        <option value="Road Glide Special -  2 Tone w/ Black Finish - FLTRXS" />
        <option value="Road Glide Special - 120th Ann w/ Black Finish - FLTRXS" />
        <option value="Road Glide Limited - Vivid Black - FLTRK" />
        <option value="Road Glide Limited - 2 Tone - FLTRK" />
        <option value="Road Glide Limited - Vivid Black w/ Black Finish - FLTRK" />
        <option value="Road Glide Limited -  Color  w/ Black Finish - FLTRK" />
        <option value="Road Glide Limited  -  2 Tone w/ Black Finish - FLTRK" />
        <option value="Ultra Limited - Vivid Black - FLHTK" />
        <option value="Ultra Limited - Color - FLHTK" />
        <option value="Ultra Limited - 2 Tone - FLHTK" />
        <option value="Ultra Limited - Vivid Black w/ Black Finish - FLHTK" />
        <option value="Ultra Limited -  Color  w/ Black Finish - FLHTK" />
        <option value="Ultra Limited  -  2 Tone w/ Black Finish - FLHTK" />
        <option value="Ultra Limited - 120th Ann w/ Chrome Finish - FLHTK" />
        <option value="Street Glide ST - Vivid Black - FLHXST" />
        <option value="Street Glide ST - Color - FLHXST" />
        <option value="Street Glide ST - 2 Tone - FLHXST" />
        <option value="Road Glide ST - Vivid Black - FLTRXST" />
        <option value="Road Glide ST - Color - FLTRXST" />
        <option value="Road Glide ST - 2 Tone - FLTRXST" />
        <option value="CVO Street Glide - Custom Color - RH975" />
        <option value="CVO Street Glide - Custom 2 Tone - RH975" />
        <option value="CVO Road Glide - Custom Color - RH975" />
        <option value="CVO Road Glide - Custom 2 Tone - RH975" />
        <option value="CVO Road Glide Limited - 120th Ann - FLTRKSEANV" />
        <option value="Freewheeler - Base - FLRT" />
        <option value="Freewheeler - Color - FLRT" />
        <option value="Freewheeler - 2-tone - FLRT" />
        <option value="Road Glide 3 - Base - FLTRT" />
        <option value="Road Glide 3 - Color - FLTRT" />
        <option value="Road Glide 3 - Black-Finish - FLTRT" />
        <option value="Tri Glide Ultra - Base - FLHTCUTG" />
        <option value="Tri Glide Ultra - Color - FLHTCUTG" />
        <option value="Tri Glide Ultra - Black-Finish - FLHTCUTG" />
        <option value="Tri Glide Ultra Ann  - Base - FLHTCUTG" />

    </datalist>
)
