import React, { useEffect, useRef, useState } from "react"
import { Outlet, Link, useFetcher, useActionData, useSubmit, Form } from "@remix-run/react"
import { LoaderFunction, redirect } from "@remix-run/node"
import { prisma } from "~/libs"
import { getSession } from "~/sessions/auth-session.server"
import { GetUser } from "~/utils/loader.server"


export async function loader({ request, params }: LoaderFunction) {
  let q = new URL(request.url).searchParams.get("q");
  if (!q) return [];
  let result;
  const getit = await prisma.workOrder.findMany({
    select: {
      workOrderId: true,
      unit: true,
      mileage: true,
      vin: true,
      tag: true,
      motor: true,
      color: true,
      budget: true,
      waiter: true,
      totalLabour: true,
      totalParts: true,
      subTotal: true,
      total: true,
      writer: true,
      userEmail: true,
      tech: true,
      discDollar: true,
      discPer: true,
      techEmail: true,
      notes: true,
      customerSig: true,
      status: true,
      location: true,
      quoted: true,
      paid: true,
      remaining: true,
      FinanceUnitId: true,
      ServiceUnitId: true,
      financeId: true,
      clientfileId: true,
      note: true,
      closedAt: true,
      createdAt: true,
      updatedAt: true,
      //  FinanceUnit
      ServiceUnit: {
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          price: true,
          brand: true,
          model: true,
          color: true,
          accessories: true,
          options: true,
          year: true,
          vin: true,
          trim: true,
          mileage: true,
          location: true,
          condition: true,
          repairs: true,
          stockNum: true,
          motor: true,
          tag: true,
          licensing: true,
          tradeEval: true,
          clientfileId: true,
        }
      },
      AccOrders: {
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          userEmail: true,
          userName: true,
          dept: true,
          sellingDept: true,
          total: true,
          discount: true,
          discPer: true,
          paid: true,
          paidDate: true,
          status: true,
          workOrderId: true,
          note: true,
          financeId: true,
          clientfileId: true,
          AccessoriesOnOrders: {
            select: {
              id: true,
              quantity: true,
              accOrderId: true,
              status: true,
              orderNumber: true,
              OrderInvId: true,
              accessoryId: true,
              service: true,
              hour: true,

              orderInventory: true,
              accessory: true,
              // accOrder
            }
          },
          Payments: {
            select: {
              id: true,
              createdAt: true,
              paymentType: true,
              cardType: true,
              amountPaid: true,
              cardNum: true,
              receiptId: true,
              financeId: true,
              userEmail: true,
              accOrderId: true,
              workOrderId: true,
              // AccOrder
              // Finance
              // WorkOrder
            }
          },
          //    WorkOrder
          //  Finance
          //  AccHandoff
          //  Clientfile
        }
      },
      Finance: {
        select: {
          financeManager: true,
          userEmail: true,
          userName: true,
          financeManagerName: true,
          email: true,
          firstName: true,
          lastName: true,
          phone: true,
          name: true,
          address: true,
          city: true,
          postal: true,
          province: true,
          dl: true,
          typeOfContact: true,
          timeToContact: true,
          dob: true,
          othTax: true,
          optionsTotal: true,
          lienPayout: true,
          leadNote: true,
          sendToFinanceNow: true,
          dealNumber: true,
          iRate: true,
          months: true,
          discount: true,
          total: true,
          onTax: true,
          on60: true,
          biweekly: true,
          weekly: true,
          weeklyOth: true,
          biweekOth: true,
          oth60: true,
          weeklyqc: true,
          biweeklyqc: true,
          qc60: true,
          deposit: true,
          biweeklNatWOptions: true,
          weeklylNatWOptions: true,
          nat60WOptions: true,
          weeklyOthWOptions: true,
          biweekOthWOptions: true,
          oth60WOptions: true,
          biweeklNat: true,
          weeklylNat: true,
          nat60: true,
          qcTax: true,
          otherTax: true,
          totalWithOptions: true,
          otherTaxWithOptions: true,
          desiredPayments: true,
          admin: true,
          commodity: true,
          pdi: true,
          discountPer: true,
          userLoanProt: true,
          userTireandRim: true,
          userGap: true,
          userExtWarr: true,
          userServicespkg: true,
          deliveryCharge: true,
          vinE: true,
          lifeDisability: true,
          rustProofing: true,
          userOther: true,
          referral: true,
          visited: true,
          bookedApt: true,
          aptShowed: true,
          aptNoShowed: true,
          testDrive: true,
          metService: true,
          metManager: true,
          metParts: true,
          sold: true,
          depositMade: true,
          refund: true,
          turnOver: true,
          financeApp: true,
          approved: true,
          signed: true,
          pickUpSet: true,
          demoed: true,
          lastContact: true,
          status: true,
          customerState: true,
          result: true,
          timesContacted: true,
          nextAppointment: true,
          followUpDay: true,
          deliveryDate: true,
          delivered: true,
          deliveredDate: true,
          notes: true,
          visits: true,
          progress: true,
          metSalesperson: true,
          metFinance: true,
          financeApplication: true,
          pickUpDate: true,
          pickUpTime: true,
          depositTakenDate: true,
          docsSigned: true,
          tradeRepairs: true,
          seenTrade: true,
          lastNote: true,
          applicationDone: true,
          licensingSent: true,
          liceningDone: true,
          refunded: true,
          cancelled: true,
          lost: true,
          dLCopy: true,
          insCopy: true,
          testDrForm: true,
          voidChq: true,
          loanOther: true,
          signBill: true,
          ucda: true,
          tradeInsp: true,
          customerWS: true,
          otherDocs: true,
          urgentFinanceNote: true,
          funded: true,
          leadSource: true,
          financeDeptProductsTotal: true,
          bank: true,
          loanNumber: true,
          idVerified: true,
          dealerCommission: true,
          financeCommission: true,
          salesCommission: true,
          firstPayment: true,
          loanMaturity: true,
          quoted: true,
          InPerson: true,
          Phone: true,
          SMS: true,
          Email: true,
          Other: true,
          paintPrem: true,
          licensing: true,
          stockNum: true,
          options: true,
          accessories: true,
          freight: true,
          labour: true,
          year: true,
          brand: true,
          mileage: true,
          model: true,
          model1: true,
          color: true,
          modelCode: true,
          msrp: true,
          trim: true,
          vin: true,
          bikeStatus: true,
          invId: true,
          motor: true,
          tag: true,
          tradeValue: true,
          tradeDesc: true,
          tradeColor: true,
          tradeYear: true,
          tradeMake: true,
          tradeVin: true,
          tradeTrim: true,
          tradeMileage: true,
          tradeLocation: true,
          lien: true,
          id: true,
          activixId: true,
          theRealActId: true,
          createdAt: true,
          updatedAt: true,
          clientfileId: true,
          inventoryMotorcycleId: true,
          InventoryMotorcycle: true,

          //financeStorage: {},
          // clientApts: {},
          //     Comm: {},
          //    FinanceDeptProducts: {},
          //      FinanceUnit: {},
          //      FinanceTradeUnit: {},
          //      AccOrders: {},
          //     WorkOrders: {},
          //     Payments: {},
          //     FinanceNote: {},
          //       Clientfile: {},
          //      finManOptions: {},
          //     bmwMotoOptions: {},
          //       uCDAForm: {},
          //        FinCanOptions: {},
        },
      },
      Clientfile: {
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          financeId: true,
          userId: true,
          firstName: true,
          lastName: true,
          name: true,
          email: true,
          phone: true,
          address: true,
          city: true,
          postal: true,
          province: true,
          dl: true,
          typeOfContact: true,
          timeToContact: true,
          conversationId: true,
          billingAddress: true,
        }
      },
      ServicesOnWorkOrders: {
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          quantity: true,
          hr: true,
          status: true,
          workOrderId: true,
          serviceId: true,
          service: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              description: true,
              estHr: true,
              service: true,
              price: true,
            }
          },

          //   WorkOrder
        }
      },
      Payments: {
        select: {
          id: true,
          createdAt: true,
          paymentType: true,
          cardType: true,
          amountPaid: true,
          cardNum: true,
          receiptId: true,
          financeId: true,
          userEmail: true,
          accOrderId: true,
          workOrderId: true,
          // AccOrder
          // Finance
          // WorkOrder
        }
      },
      WorkOrderApts: {
        select: {
          id: true,
          tech: true,
          techEmail: true,
          writer: true,
          start: true,
          end: true,
          title: true,
          workOrderId: true,
          completed: true,
          resourceId: true,
          unit: true,
          mileage: true,
          vin: true,
          tag: true,
          motor: true,
          color: true,
          location: true,
          createdAt: true,
          updatedAt: true,
          // WorkOrder
        }
      },
      WorkOrderClockEntries: {
        select: {
          id: true,
          start: true,
          end: true,
          userEmail: true,
          username: true,
          workOrderId: true,
          createdAt: true,
          updatedAt: true,
          //  WorkOrder
        }
      },
    }
  });
  result = getit.filter(
    (result) =>
      result.workOrderId === parseInt(q)
  );
  return result;
}
