import { LoaderFunction } from "@remix-run/node";
import { prisma } from "~/libs";

export async function loader({ request, params }: LoaderFunction) {
  const id = params.orderId
  const order = await prisma.accOrder.findUnique({
    where: { id: id },
    select: {
      id: true,
      createdAt: true,
      updatedAt: true,
      userEmail: true,
      userName: true,
      dept: true,
      sellingDept: true,
      total: true,
      discount: true,
      discPer: true,
      paid: true,
      paidDate: true,
      status: true,
      workOrderId: true,
      note: true,
      financeId: true,
      clientfileId: true,
      Clientfile: {
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          financeId: true,
          userId: true,
          firstName: true,
          lastName: true,
          name: true,
          email: true,
          phone: true,
          address: true,
          city: true,
          postal: true,
          province: true,
          dl: true,
          typeOfContact: true,
          timeToContact: true,
          conversationId: true,
          billingAddress: true,
          dob: true,
        },
      },
      AccessoriesOnOrders: {
        select: {
          id: true,
          quantity: true,
          accOrderId: true,
          accessoryId: true,
          status: true,
          orderNumber: true,
          OrderInvId: true,
          service: true,
          hour: true,
          accessory: {
            select: {
              id: true,
              createdAt: true,
              updatedAt: true,
              partNumber: true,
              brand: true,
              name: true,
              price: true,
              cost: true,
              quantity: true,
              minQuantity: true,
              description: true,
              category: true,
              subCategory: true,
              onOrder: true,
              distributer: true,
              location: true,
              note: true,
              workOrderSuggestion: true,
            },
          },
        },
      },
      Payments: {
        select: {
          id: true,
          createdAt: true,
          paymentType: true,
          cardType: true,
          amountPaid: true,
          cardNum: true,
          receiptId: true,
          financeId: true,
          userEmail: true,
          accOrderId: true,
          workOrderId: true,
        },
      },
    },
  });
  return order
}
