export const KawasakiList = () => (
	<datalist id="ListOptions2">
		<option value="KX65" />
		<option value="KX85" />
		<option value="KX112" />
		<option value="KX250" />
		<option value="KX450" />
		<option value="KX450SR" />
		<option value="KX250X" />
		<option value="KX250X" />
		<option value="KLX110R" />
		<option value="KLX140R" />
		<option value="KLX230R" />
		<option value="KLX300" />
		<option value="KLX230" />
		<option value="KLX300" />
		<option value="KLX300SM" />
		<option value="VULCAN S " />
		<option value="VULCAN 900" />
		<option value="VULCAN 1700 VAQUERO" />
		<option value="VULCAN 1700 VOYAGER" />
		<option value="EMILINATOR" />
		<option value="CONCOURSE" />
		<option value="W800" />
		<option value="VERSYS-X 300" />
		<option value="VERSYS 650" />
		<option value="VERSYS 1000" />
		<option value="Z H2 " />
		<option value="Z400" />
		<option value="Z650 " />
		<option value="Z900" />
		<option value="Z650RS" />
		<option value="Z900RS " />
		<option value="Z125 PRO" />
		<option value="NINJA H2 SX " />
		<option value="NINJA H2" />
		<option value="NINJA H2R" />
		<option value="NINJA ZX-4R" />
		<option value="NINJA ZX-6R" />
		<option value="NINJA ZX-10R" />
		<option value="NINJA ZX-14R" />
		<option value="NINJA 400 " />
		<option value="NINJA 650" />
		<option value="NINJA 1000SX" />
		<option value="KFX50" />
		<option value="KSX90" />
		<option value="BRUTE FORCE 300" />
		<option value="BRUTE FORCE 750" />
		<option value="TERYX KRX 1000" />
		<option value="TERYX KRX4 1000" />
		<option value="TERYX " />
		<option value="TERYX4" />
		<option value="MULE 4010 TRANS 4X4" />
		<option value="MULE SX" />
		<option value="MULE 4010 4X4" />
		<option value="MULE PRO-MX" />
		<option value="MULE PRO-FXT 1000" />
		<option value="MULE PRO-FXT" />
		<option value="MULE PRO-DXT DIESEL" />
		<option value="MULE PRO-FX 1000" />
		<option value="MULE PRO-FXR 1000" />
		<option value="MULE PRO-FX" />
		<option value="MULE PRO-DX DIESEL" />
		<option value="MULE PRO-FXR 1000" />
		<option value="JET SKI SX-R 160" />
		<option value="JET SKI ULTRA 160" />
		<option value="JET SKI ULTRA LX " />
		<option value="JET SKI STX 160" />
		<option value="JET SKI ULTRA 310LX " />
		<option value="JET SKI ULTRA 310X" />
	</datalist>
)
