export const SuzukiList = () => (
  <datalist id="ListOptions2">
    <option value="hayabusa gsx1300rrqm3" />
    <option value="gsx-rioooam3" />
    <option value="gsx-rioooram3" />
    <option value="gsx-k1000rzam3" />
    <option value="gsx-r750m3" />
    <option value="gsx-r750zm3" />
    <option value="gsx-r600m3" />
    <option value="gsx-r600zm3" />
    <option value="katana gsx-siooosrqm3" />
    <option value="gsx-s1000m3" />
    <option value="gsx-s1000gtm3" />
    <option value="gsx-s1000gtam3 touring kit" />
    <option value="gsx-s750am3" />
    <option value="gsx-s750zam3" />
    <option value="gsx-8sm3" />
    <option value="sv650am3" />
    <option value="sv650xam3" />
    <option value="v-strom 1050 dl1050rrm3" />
    <option value="v-strom 1050 de dl1050rjm3" />
    <option value="v-strom 1050de dl1050rjm3 adventure kit" />
    <option value="v-strom 650" />
    <option value="v-strom 650xt" />
    <option value="v-strom adventure kit" />
    <option value="v-strom dl800de" />
    <option value="dr650sem3" />
    <option value="dr-z400smm3 supermoto" />
    <option value="dr-z400sm3" />
    <option value="boulevard m109r b.o.s.s. vzr1800bzm3" />
    <option value="boulevard c50t vl800tm3" />
    <option value="boulevard c50 vl800m3" />
    <option value="burgman 400 an400am3" />
    <option value="dr-z125lm3" />
    <option value="dr-z125m3" />
    <option value="dr-z50m3" />
    <option value="rm-z450m3" />
    <option value="rm-z250m3" />
    <option value="rm85m3t" />
    <option value="LT-A750XM3 Flame Red (YT9)" />
    <option value="LT-A750XPM3 Flame Red (YT9)" />
    <option value="LT-A750XPM3 Terra Green(YLG)" />
    <option value="LT-A750XPZM3 Great Blue (YPW)" />
    <option value="LT-A750XPZSM3 Metallic Mat Rocky Gray(QTF)" />
    <option value="LT-A750XPZSM3 Cast Carbon(QZ8)" />
    <option value="LT-A750XPZCM3 True Timber Kanati(QTM)" />
    <option value="LT-A500XM3 Terra Green(YLG)" />
    <option value="LT-A500XPM3 Flame Red(YT9)" />
    <option value="LT-A500XPM3 Terra Green(YLG)" />
    <option value="LT-A500XPZM3 Great Blue (YPW)" />
    <option value="LT-A500XPZSM3 Metallic Mat Rocky Gray(QTF)" />
    <option value="LT-A500XPZSM3 Cast Carbon(QZ8)" />
    <option value="LT-A500XPZCM3 True Timber Kanati(QTM)" />
    <option value="LT-A400FSM3 Metallic Mat Rocky Gray(QTF)" />
    <option value="LT-A400FM3 Flame Red(YT9)" />
    <option value="LT-F400FM3 Terra Green(YLG)" />
    <option value="LT-Z90M3 Champion Yellow No 2 (YU1)" />
    <option value="LT-Z50M3 Champion Yellow No 2 (YU1)" />
  </datalist>
);
