
export const TriumphList = () => (
	<datalist id="ListOptions">
		<option value="TIGER 900 GT ARAGON ED" />
		<option value="TIGER 900 GT - WHITE" />
		<option value="TIGER 900 GT - BLACK" />
		<option value="TIGER 900 GT - BLUE" />
		<option value="TIGER 900 GT LOW - WHITE" />
		<option value="TIGER 900 GT LOW - BLACK" />
		<option value="TIGER 900 GT LOW - BLUE" />
		<option value="TIGER 900 GT PRO - WHITE" />
		<option value="TIGER 900 GT PRO - BLACK" />
		<option value="TIGER 900 GT PRO - BLUE" />
		<option value="TIGER 900 RALLY ARAGON ED" />
		<option value="TIGER 900 RALLY - WHITE" />
		<option value="TIGER 900 RALLY - SANDSTORM" />
		<option value="TIGER 900 RALLY - BLACK" />
		<option value="TIGER 900 RALLY PRO - WHITE" />
		<option value="TIGER 900 RALLY PRO - SANDSTORM" />
		<option value="TIGER 900 RALLY PRO - BLACK" />
		<option value="T120 BLACK DGR LE" />
		<option value="ROCKET 3 221" />
		<option value="ROCKET 3 GT 221" />
		<option value="TIGER SPORT 660 - BLUE" />
		<option value="TIGER SPORT 660 - RED " />
		<option value="TIGER 850 SPORT" />
		<option value="TIGER 900 GT RANGE" />
		<option value="TIGER 900 RALLY RANGE " />
		<option value="TIGER 1200 GT " />
		<option value="TIGER 1200 RALLY " />
		<option value="SPEED TWIN 900" />
		<option value="SPEED TWIN 900 - IRONSTONE" />
		<option value="SPEED TWIN 900 - SILVER ICE" />
		<option value="SPEED TWIN 900 CHROME ED" />
		<option value="BONNEVILLE T100" />
		<option value="BONNEVILLE T100 - ORANGE" />
		<option value="BONNEVILLE T100 - RED" />
		<option value="BONNEVILLE T100 CE" />
		<option value="SCRAMBLER 900 " />
		<option value="BONNEVILLE T120" />
		<option value="BONNEVILLE T120 - BLUE" />
		<option value="BONNEVILLE T120 - RED" />
		<option value="BONNEVILLE T120 CE " />
		<option value="BONNEVILLE T120 BLACK" />
		<option value="BONNEVILLE T120 BLACK GL" />
		<option value="SPEED TWIN 1200" />
		<option value="SPEED TWIN 1200 - ORANGE" />
		<option value="SPEED TWIN 1200 - RED" />
		<option value="SCRAMBLER 1200 XC" />
		<option value="SCRAMBLER 1200 XC - RED" />
		<option value="SCRAMBLER 1200 XC - GREEN" />
		<option value="SCRAMBLER 1200 XE" />
		<option value="SCRAMBLER 1200 XE - RED" />
		<option value="SCRAMBLER 1200 XE - GREEN" />
		<option value="SCRAMBLER 1200 XE CE" />
		<option value="SCRAMBLER 1200 XC GL" />
		<option value="BONNEVILLE BOBBER" />
		<option value="BONNEVILLE BOBBER - RED" />
		<option value="BONNEVILLE BOBBER - GREY" />
		<option value="BONNEVILLE BOBBER CHROME ED" />
		<option value="BONNEVILLE SPEEDMASTER" />
		<option value="BONNEVILLE SPEEDMASTER - RED" />
		<option value="BONNEVILLE SPEEDMASTER - WHITE" />
		<option value="BONNEVILLE SPEEDMASTER CE" />
		<option value="THRUXTON RS " />
		<option value="THRUXTON RS - GREEN" />
		<option value="THRUXTON RS CE" />
		<option value="TRIDENT 660" />
		<option value="TRIDENT 660 - COLOR" />
		<option value="STREET TRIPLE" />
		<option value="STREET TRIPLE MOTO 2 ED" />
		<option value="SPEED TRIPLE 1200 RS " />
		<option value="SPEED TRIPLE 1200 RS - ORANGE" />
		<option value="SPEED TRIPLE 1200 RR" />
		<option value="SPEED TRIPLE 1200 RR - RED" />
		<option value="STREET TRIPLE R" />
		<option value="STREET TRIPLE R - WHITE" />
		<option value="STREET TRIPLE RS " />
		<option value="STREET TRIPLE RS - RED YELLOW" />
		<option value="ROCKET 3 R" />
		<option value="ROCKET 3 R - RED" />
		<option value="ROCKET 3 R - RED/SILVER" />
		<option value="ROCKET 3 R CE" />
		<option value="ROCKET 3 GT" />
		<option value="ROCKET 3 GT - RED" />
		<option value="ROCKET 3 GT CE" />
	</datalist>
)
